### ISSUE TITLE
npm package broken TS1128: Declaration or statement expected.

### ISSUE THREAD

**Issue by alex-vg** [xan105/node-powertoast#10]
If you `npm install -D powertoast` and use the lib with Typescript, you get an error `\node_modules\powertoast\types\index.d.ts(55,1) TS1128: Declaration or statement expected.`

I can see that this already has been fixed here but is still broken in the npm package 2.1.4.

Could you kindly release a new version, please?

**Comment by xan105** [comment]
I've updated the npm package (_2.1.5_).
Sorry for the inconvenience.

I'm still new to typescript, if there are other mistakes or problem let me know and I'll try to fix it.
