### ISSUE TITLE
use powerShell evaluation possibly wrong

### ISSUE THREAD

**Issue by smadep** [xan105/node-powertoast#2]
Hi!

const powerShell = (!winRT || (winRT && option.disableWinRT === true)) ? false : true;

... shouldn't that line have reversed returns?!    
in case of either no winRT or (winRT but disabled-option) then use powershell otherwise not.

const powerShell = (!winRT || (winRT && option.disableWinRT === true)) ? **true** : **false**;

Thanks, Stefan

**Comment by xan105** [comment]
Damn how did I miss that 😰 Thanks man.
