### ISSUE TITLE
I'm trying to use but.

### ISSUE THREAD

**Issue by dsrdan** [xan105/node-powertoast#5]
Hi. thanks for this powertoast.
I'm trying to use but, some question.

toast({
  appID: "MSEdge",
  title: "App notify",
  message: "There is new message",
  attribution: "App",
  icon: "app.png",
  cropIcon: true,
  onClick: "https://www.naver.com"
}).catch(err => console.error(err));

Everything is fine but.
When click, "https://www.naver.com" is opened as background window if default browser is opened already.
If there is no default browser running, "https://www.naver.com" is opened and become a foreground window.
I want click event makes link become a foreground window whether default browser is running or not.
How I'm do something?

Sorry for my poor english.
Can you help me?

**Comment by xan105** [comment]
This is normal Windows behavior. I don't think there is any way to have control over this outside of the browser's settings.
